version: b{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run package-win

test: off

deploy:
  provider: GitHub
  auth_token:
    secure: 3aQM4eQwpFvNNftJYWFOsF7jAl6svWY1xjFSxUR0npeVJl65TLmiTgrjw0iU5xtU
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
