version: b{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run package-win

test: off

deploy:
  provider: GitHub
  auth_token:
    secure: pEuxMVBcXVR+mpN/lHIjk0G+zYvvzvF+U6Zt2RUl0j96BcqCdJEBJ627St6yVN8Y
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
