version: '3.7'
services:
  android-build:
    container_name: mobile-android-build
    build:
      context: ./build-container
      network: host
      dockerfile: Dockerfile
    volumes:
      - ./:/mobile
