version: '3.5'

services:
  couchdb:
    image: couchdb:3.2.1
    container_name: idai-field-server_couchdb
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    networks:
      - web
      - default
    deploy:
      labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.port=5984"

  field_hub:
    image: "ghcr.io/dainst/field_hub:${FIELD_HUB_VERSION}"
    container_name: idai-field-server_fieldhub
    environment:
      - HOST
      - SECRET_KEY_BASE
      - COUCHDB_ADMIN_NAME=${COUCHDB_USER}
      - COUCHDB_ADMIN_PASSWORD=${COUCHDB_PASSWORD}
    depends_on:
      - "couchdb"
    volumes:
      - file-data:/files
    networks:
      - web
      - default
    deploy:
      labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.port=4000"

volumes:
  file-data:
    name: idai-field-server_files
    external: true
    

networks:
  web:
    external: true