version: "3.7"

services:

  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: abcdef
    ports: 
      - "5432:5432"

  couchdb:
    image: couchdb:3

  api:
    build: .
    ports:
      - "4000:4000"

