version: "3.7"

services:

  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - 'COUCHDB_USER=synctest'
      - 'COUCHDB_PASSWORD=abcdef'
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:db.field.idai.world"
        - "traefik.port=5984"

  server:
    image: "dainst/idai-field-web-server"
    build: .
    ports:
      - "4000:4000"
    environment:
      - IN_CONTAINER=true
    volumes:
      - "./config:/opt/src/server/config"
      - "./resources:/opt/src/server/resources"
      - "./lib:/opt/src/server/lib"
      - "./test:/opt/src/server/test"
      - "./assets:/opt/src/server/assets"
      - "./_build:/opt/src/server/_build"
