version: "3.7"

services:

  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=abcdef'
    volumes:
      - "couchdb-data:/opt/couchdb/data"
  
  server:
    image: "dainst/idai-field-web-server"
    ports:
      - "4400:4000"
    volumes:
      - "server-config:/opt/src/server/config"
      - "server-images:/opt/src/server/files"
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:server.field.idai.world"
        - "traefik.port=4000"
  
volumes:
  couchdb-data:
  server-config:
  server-images:

networks:
  web:
    external: true
