version: '3.5'

services:

  cantaloupe:
    image: "ghcr.io/dainst/field_publication_cantaloupe:latest"
    environment:
      LOG_APPLICATION_LEVEL: warn
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    volumes:
      - "file-data:/files"
    networks:
      - default

  couchdb:
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=${COUCHDB_ADMIN_NAME}
      - COUCHDB_PASSWORD=${COUCHDB_ADMIN_PASSWORD}
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - default

  app:
    image: "ghcr.io/dainst/field_publication:${FIELD_PUBLICATION_VERSION}"
    environment:
      - HOST
      - SECRET_KEY_BASE
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_ADMIN_NAME=${COUCHDB_ADMIN_NAME}
      - COUCHDB_ADMIN_PASSWORD=${COUCHDB_ADMIN_PASSWORD}
    depends_on:
      - "couchdb"
    volumes:
      - file-data:/files
    networks:
      - web
      - default
    deploy:
      labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.port=4000"

  opensearch: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:2.11.1 # Specifying the latest available image - modify if you want a specific version
    environment:
      - discovery.type=single-node
      - plugins.security.ssl.http.enabled=false
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        # Set memlock to unlimited (no soft or hard limit)
        soft: -1 
        hard: -1
      nofile:
        # Maximum number of open files for the opensearch user - set to at least 65536
        soft: 65536 
        hard: 65536

volumes:
  file-data:
    name: idai_field_publication_files
    external: true
  db-data:
    name: idai_field_publication_database
    external: true
  opensearch-data:
    name: idai_field_publication_search_index
    external: true

networks:
  web:
    external: true