name: build-mobile
on:
  push:
    paths:
    - "core/**"
    - "mobile/**"
    - ".github/workflows/build-mobile.yml"
jobs:
  build-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Setup NPM cache
        uses: c-hive/gha-npm-cache@v1
      - name: Install root node modules
        run: npm i
      - name: Bootstrap monorepo packages
        run: npm run bootstrap
      - name: Build core
        run: npm run build
        working-directory: core
      - name: Build mobile
        run: npm run build
        working-directory: mobile
      - name: Unit test mobile
        run:  npm test
        working-directory: mobile
      - name: Export App
        run: npm run export
        working-directory: mobile
      - name: Build Android app
        run: docker-compose run android-build
        working-directory: mobile
