name: Server
on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server.yml"
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/server.yml"
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          elixir-version: 1.13.4
      - name: Start CouchDB
        run: docker-compose -f docker-compose.yml --env-file .env_template up -d
        working-directory: server
      - name: Wait 10 seconds for CouchDB startup
        run: sleep 10s
      - name: Install FieldHub dependencies
        run: mix deps.get
        working-directory: server
      - name: Run FieldHub tests
        run: mix test
        working-directory: server
      - name: Stop CouchDB
        run: docker-compose -f docker-compose.yml --env-file .env_template down -v
        working-directory: server
