name: Server / Tests
on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/tests-server.yml"
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/tests-server.yml"
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          elixir-version: 1.12.3
      - name: Install inotify-tools
        run: sudo apt-get install inotify-tools
      - name: Setup server
        run: mix setup
        working-directory: server
      - name: Run server tests
        run: mix test
        working-directory: server
