name: Desktop / Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Main:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm run bootstrap
      - name: Build core
        run: npm run build
        working-directory: core
      - name: Build desktop tests
        run: npm run build:test
        working-directory: desktop
      - name: Run core unit tests
        run: npm run test
        working-directory: core
      - name: Run desktop unit tests
        run: npm run test
        working-directory: desktop
      - name: Run FieldHub integration tests
        run: npm run test:hub-integration
        working-directory: desktop
      - name: Run Java tools tests
        run: mvn -f java/pom.xml test
        working-directory: desktop
  e2e:
    timeout-minutes: 90
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm run bootstrap
      - name: Build core
        run: npm run build
        working-directory: core
      - name: Run e2e tests
        run: npm run e2e
        working-directory: desktop
